# Generated by Django 5.1 on 2024-11-21 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь (м²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='floor',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='square',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Квадратура (м²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='term',
            field=models.PositiveIntegerField(default=1, help_text='Укажите срок в месяцах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок (месяцы)'),
            preserve_default=False,
        ),
    ]
