# Generated by Django 5.1 on 2024-11-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_furniture_area_furniture_floor_furniture_square_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коммерческого строения')),
            ],
            options={
                'verbose_name': 'Коммерческое строение',
                'verbose_name_plural': 'Коммерческие строения',
            },
        ),
        migrations.CreateModel(
            name='GardenAndOutbuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название садового и хозпостроения')),
            ],
            options={
                'verbose_name': 'Садовое и хозпостроение',
                'verbose_name_plural': 'Садовые и хозпостройки',
            },
        ),
        migrations.CreateModel(
            name='HouseAndResidentialBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жилого строения')),
            ],
            options={
                'verbose_name': 'Дом и жилое строение',
                'verbose_name_plural': 'Дома и жилые строения',
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='commercial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='furniture.commercialbuilding', verbose_name='Коммерческое строение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='garden',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='furniture.gardenandoutbuildings', verbose_name='Садовое и хозпостроение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='house',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='furniture.houseandresidentialbuilding', verbose_name='Дом и жилое строение'),
            preserve_default=False,
        ),
    ]
